config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  root 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


  # delete '/doses/:id', to: 'doses#destroy', as: 'dose'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader

  def image
    if photo.present?
      photo
    else
      "https://images.unsplash.com/photo-1509669803555-fd5edd8d5a41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"
    end
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @dose = Dose.new
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
    @dose = Dose.new
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end
  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing <%= @cocktail.name %></h1>


<!-- Ingredient-->
<div class="container">
  <div>
    <div>
      <div>
        <%= simple_form_for @cocktail do |f| %>
          <p> Be serious on your description doses</p>
          <%= f.input :name %>
          <p>Change your photo </p>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Submit"%>
        <% end %>
      </div>
    </div>
  </div>
</div>




<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.fraichementpresse.ca/image/policy:1.1818440:1522338959/3-cocktails-rhum-brun.png?w=700&$p$w=36d7d67);">
  <h1>Great Cocktails</h1>

  <p class="text-center">
    <span id="banner-typed-text"></span>
  </p>
</div>

<!--
<%= cl_image_tag("c8lwtm2bhvykdp0tfve2", width: 400, height: 300, crop: :fill) %>

<%= cl_image_tag("eamq3jkbwb3e6e3807dh",width: 150, height: 150, crop: :thumb, gravity: :face) %>
 -->


  <div class="container">
    <div class="grid">
      <% @cocktails.each do |cocktail| %>
        <div class="card-trip">
          <!-- fonction image faite dans le model cocktail -->
          <%= cl_image_tag cocktail.image %>
          <div class="card-trip-infos">
            <div>
              <h2><%= cocktail.name %></h2>
              <p>Ready to drink</p>
              <%= link_to "", cocktail_path(cocktail), class: "far fa-eye" %>
              <%= link_to "", edit_cocktail_path(cocktail), class: "far fa-edit"  %>
            </div>
            <%= link_to "", cocktail, method: :delete, data: {confirm: "Are you sure ?"}, class: "card-trip-pricing far fa-trash-alt" %>
            <img src="https://assets.afcdn.com/recipe/20180705/80274_w1024h768c1cx2378cy1278cxt0cyt0cxb4799cyb3199.jpg" class="card-trip-user avatar-bordered" />
          </div>
        </div>
      <% end %>
      <div class="plus">
        <div class="plus1">
          <%= link_to "", new_cocktail_path, class: "fas fa-plus" %>
        </div>
      </div>
    </div>
  </div>

app/views/cocktails/new.html.erb
<div>
  <h1>Add new cocktail</h1>
  <div>
    <div>
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "Submit"%>
        <% end %>
        <div>
          <%= link_to "Back", cocktails_path %>
        </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">

  <h1> <%= @cocktail.name %> </h1>
  <%= cl_image_tag @cocktail.image, height: 300, width: 400, crop: :fill %>

  <!-- Ingredient-->
  <div>
    <% if @cocktail.doses.empty? %>
      <p>
        No ingredient, sorry, do you want to add some ingredients ?
      </p>
      <div>
        <div>
          <div>
            <%= simple_form_for [@cocktail, @dose] do |f| %>
              <%= f.association :ingredient %>
              <p> Be serious on your description doses</p>
              <%= f.input :description %>
              <%= f.submit "Submit"%>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
    <h3> Ingredients </h2>
    <ul>

      <% @cocktail.doses.each do |dose| %>
      <li>
        <strong>Ingredient: <%= dose.ingredient.name %> </strong>
        <%= link_to "Delete", dose_path(dose), method: :delete  %>
      </li>
        <p>Dose description: <%= dose.description %></p>
      <% end %>
    </ul>
    <% end %>
  </div>

  <!--Back to cocktail list  -->
  <div>
    <%= link_to "Back to cocktail list", cocktails_path %>
  </div>

</div>

app/views/doses/new.html.erb
<div>
  <h3>Add an ingredient</h1>
  <div>
    <div >
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient %>
      <%= f.input :description %>
      <%= f.submit "Submit"%>
      <% end %>
      <div>
        <%= link_to "Back", cocktails_path%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>